#!/usr/bin/env node
// Read .env, substitute ${PLACEHOLDER} tokens in wrangler.example.jsonc,
// write the result to wrangler.jsonc. Idempotent — safe to re-run.
//
// No npm dependencies; uses only Node built-ins.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const ROOT = join(SCRIPT_DIR, "..");
const ENV_PATH = join(ROOT, ".env");
const TEMPLATE_PATH = join(ROOT, "wrangler.example.jsonc");
const OUT_PATH = join(ROOT, "wrangler.jsonc");

const REQUIRED = ["CLOUDFLARE_ACCOUNT_ID", "RESOLVER_HOSTNAME", "VAULT_NAME"];

function parseEnv(text) {
  const out = {};
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq < 0) continue;
    const key = line.slice(0, eq).trim();
    let val = line.slice(eq + 1).trim();
    if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }
    out[key] = val;
  }
  return out;
}

function main() {
  if (!existsSync(ENV_PATH)) {
    console.error("error: .env not found.");
    console.error("       cp .env.example .env, then edit .env to fill in your values.");
    process.exit(1);
  }

  if (!existsSync(TEMPLATE_PATH)) {
    console.error(`error: ${TEMPLATE_PATH} not found.`);
    process.exit(1);
  }

  const env = parseEnv(readFileSync(ENV_PATH, "utf8"));
  const missing = REQUIRED.filter((k) => !env[k]);
  if (missing.length) {
    console.error(`error: .env is missing required values: ${missing.join(", ")}`);
    process.exit(1);
  }

  let out = readFileSync(TEMPLATE_PATH, "utf8");
  // Replace the template header with a generated-file warning. The header
  // is the run of `//` comments at the top of the file.
  out = out.replace(
    /^(\/\/[^\n]*\n)+/,
    "// Generated by scripts/setup.mjs from wrangler.example.jsonc + .env.\n" +
    "// Edit .env and rerun `npm run setup` rather than editing this file.\n",
  );
  out = out.replace(/\$\{([A-Z_][A-Z0-9_]*)\}/g, (match, key) => {
    if (!(key in env)) {
      console.error(`error: template references \${${key}} but .env has no such key.`);
      process.exit(1);
    }
    return env[key];
  });

  writeFileSync(OUT_PATH, out);
  console.log(`wrote ${OUT_PATH}`);
  console.log("next: npx wrangler whoami  (confirm account)");
  console.log("      npm test              (verify)");
  console.log("      npx wrangler deploy   (deploy)");
}

main();
