// Stateless HTTP → obsidian:// redirector. Reads nothing, writes nothing,
// stores nothing. Three routes:
//
//   GET /n/<id>             → 302 obsidian://advanced-uri?vault=<NAME>&uid=<id>
//   GET /p/?path=<path>     → 302 obsidian://open?vault=<NAME>&file=<path>
//   GET /f/<name>           → 302 obsidian://open?vault=<NAME>&file=<name>
//
// Threat model is NOT classic open-redirect — the only target scheme is
// obsidian://. Real threat is reflected/unvalidated input injected as extra
// `&param=` into Advanced URI by way of links sitting in externally-writable
// systems (tickets, synced to-dos) that the user later clicks. Defenses:
//
//   1. Anchored allowlist regex per route. Anything not matching → 400.
//   2. encodeURIComponent on the one variable before interpolation. Always.
//   3. Vault name comes from env, never input. Location is constant scheme +
//      constant query keys + one encoded variable. No reflection.
//   4. Fail closed — no fallback redirect on bad input.

// `Env` is the ambient type generated by `wrangler types` from wrangler.jsonc
// vars; see worker-configuration.d.ts.

// 21-char nanoid in URL-safe alphabet — matches the MCP's minter.
const NANOID_RE = /^[A-Za-z0-9_-]{21}$/;
// Strict UUIDv4 — the format Advanced URI mints when "Copy URI" is run on a
// note that has no id yet. Version nibble = 4, variant nibble in {8,9,a,b}.
// Case-insensitive hex. Tighter than "any UUID" by design: rejects v1/v3/v5,
// the NIL UUID, and the MAX UUID, which AU does not produce.
const UUID_V4_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$/;

// Conservative filename charset: letters, digits, space, and a small set of
// safe punctuation. No slashes, no `& ? # =`, no control chars, no quotes.
// Length cap 200.
const FILENAME_RE = /^[A-Za-z0-9 .,_'!()+~-]{1,200}$/;

// Path: must end in `.md`, may contain forward slashes for sub-paths, plus
// the same conservative charset above. No `..`, no leading `/` or `\`, no
// `& ? # =`, no control chars.
const PATH_SEGMENT_CHARS = "A-Za-z0-9 .,_'!()+~-";
const PATH_RE = new RegExp(`^(?:[${PATH_SEGMENT_CHARS}]+/)*[${PATH_SEGMENT_CHARS}]+\\.md$`);

function plain(body: string, status: number): Response {
  return new Response(body, {
    status,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store",
    },
  });
}

function redirect(location: string): Response {
  return new Response(null, {
    status: 302,
    headers: {
      Location: location,
      "Cache-Control": "no-store",
    },
  });
}

function buildAdvancedUriUidRedirect(env: Env, id: string): string {
  return `obsidian://advanced-uri?vault=${encodeURIComponent(env.VAULT_NAME)}&uid=${encodeURIComponent(id)}`;
}

function buildOpenFileRedirect(env: Env, fileOrPath: string): string {
  return `obsidian://open?vault=${encodeURIComponent(env.VAULT_NAME)}&file=${encodeURIComponent(fileOrPath)}`;
}

function handleN(env: Env, idRaw: string): Response {
  if (!NANOID_RE.test(idRaw) && !UUID_V4_RE.test(idRaw)) return plain("invalid", 400);
  return redirect(buildAdvancedUriUidRedirect(env, idRaw));
}

function handleP(env: Env, url: URL): Response {
  const path = url.searchParams.get("path");
  if (path === null || path.length === 0) return plain("invalid", 400);
  if (path.includes("..")) return plain("invalid", 400);
  if (path.startsWith("/") || path.startsWith("\\")) return plain("invalid", 400);
  if (!PATH_RE.test(path)) return plain("invalid", 400);
  return redirect(buildOpenFileRedirect(env, path));
}

function handleF(env: Env, nameRaw: string): Response {
  // Path segment came in already URL-decoded by `new URL().pathname` split.
  // Reject embedded slashes (the route is single-segment anyway, but be
  // defensive against `decodeURIComponent` surprises).
  if (nameRaw.length === 0) return plain("invalid", 400);
  if (nameRaw.includes("/") || nameRaw.includes("\\")) return plain("invalid", 400);
  if (!FILENAME_RE.test(nameRaw)) return plain("invalid", 400);
  return redirect(buildOpenFileRedirect(env, nameRaw));
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("method not allowed", {
        status: 405,
        headers: { "Content-Type": "text/plain; charset=utf-8", Allow: "GET, HEAD" },
      });
    }

    const url = new URL(request.url);
    const path = url.pathname;

    if (path === "/" || path === "") {
      return plain("obsidian link resolver", 200);
    }

    // /n/<id> — nanoid alphabet is all URL-safe, so the raw path segment is
    // compared directly. Any percent-encoded bytes would fail the regex.
    if (path.startsWith("/n/")) {
      const rest = path.slice(3);
      if (rest.includes("/")) return plain("invalid", 400);
      return handleN(env, rest);
    }

    // /p/?path=...
    if (path === "/p/" || path === "/p") {
      return handleP(env, url);
    }

    // /f/<name>
    if (path.startsWith("/f/")) {
      const rest = path.slice(3);
      if (rest.includes("/")) return plain("invalid", 400);
      let name: string;
      try {
        name = decodeURIComponent(rest);
      } catch {
        return plain("invalid", 400);
      }
      return handleF(env, name);
    }

    return plain("invalid", 400);
  },
};
